import type { CameraType, LensType, FilmStock } from "./types";

export const cameraTypes: CameraType[] = [
  {
    id: "olympus-om-10",
    dataSource: "system",
    make: "Olympus",
    model: "OM-10",
    type: "SLR",
    filmFormat: "35mm",
    mount: "OM",
    disposable: false,
    halfFrame: false,
    releaseDate: "1979",
    minShutterSpeed: 1 / 1000,
    maxShutterSpeed: 1,
  },
  {
    id: "olympus-om-30",
    dataSource: "system",
    make: "Olympus",
    model: "OM-30",
    type: "SLR",
    filmFormat: "35mm",
    mount: "OM",
    disposable: false,
    halfFrame: false,
    releaseDate: "1983",
    minShutterSpeed: 1 / 1000,
    maxShutterSpeed: 1,
  },
  {
    id: "nikon-f3",
    dataSource: "system",
    make: "Nikon",
    model: "F3",
    type: "SLR",
    filmFormat: "35mm",
    mount: "F",
    disposable: false,
    halfFrame: false,
    releaseDate: "1980",
    minShutterSpeed: 1 / 2000,
    maxShutterSpeed: 1,
  },
  {
    id: "canon-ae1",
    dataSource: "system",
    make: "Canon",
    model: "AE-1",
    type: "SLR",
    filmFormat: "35mm",
    mount: "FD",
    disposable: false,
    halfFrame: false,
    releaseDate: "1976",
    minShutterSpeed: 1 / 1000,
    maxShutterSpeed: 1,
  },
  {
    id: "pentax-k1000",
    dataSource: "system",
    make: "Pentax",
    model: "K1000",
    type: "SLR",
    filmFormat: "35mm",
    mount: "K",
    disposable: false,
    halfFrame: false,
    releaseDate: "1976",
    minShutterSpeed: 1 / 1000,
    maxShutterSpeed: 1,
  },
  {
    id: "minolta-x-700",
    dataSource: "system",
    make: "Minolta",
    model: "X-700",
    type: "SLR",
    filmFormat: "35mm",
    mount: "SR",
    disposable: false,
    halfFrame: false,
    releaseDate: "1981",
    minShutterSpeed: 1 / 1000,
    maxShutterSpeed: 1,
  },
  {
    id: "leica-r6",
    dataSource: "system",
    make: "Leica",
    model: "R6",
    type: "SLR",
    filmFormat: "35mm",
    mount: "R",
    disposable: false,
    halfFrame: false,
    releaseDate: "1988",
    minShutterSpeed: 1 / 2000,
    maxShutterSpeed: 1,
  },
  {
    id: "nikon-fm2",
    dataSource: "system",
    make: "Nikon",
    model: "FM2",
    type: "SLR",
    filmFormat: "35mm",
    mount: "F",
    disposable: false,
    halfFrame: false,
    releaseDate: "1982",
    minShutterSpeed: 1 / 4000,
    maxShutterSpeed: 1,
  },
  {
    id: "canon-f-1",
    dataSource: "system",
    make: "Canon",
    model: "F-1",
    type: "SLR",
    filmFormat: "35mm",
    mount: "FD",
    disposable: false,
    halfFrame: false,
    releaseDate: "1971",
    minShutterSpeed: 1 / 2000,
    maxShutterSpeed: 1,
  },
  {
    id: "pentax-mx",
    dataSource: "system",
    make: "Pentax",
    model: "MX",
    type: "SLR",
    filmFormat: "35mm",
    mount: "K",
    disposable: false,
    halfFrame: false,
    releaseDate: "1976",
    minShutterSpeed: 1 / 1000,
    maxShutterSpeed: 1,
  },
  {
    id: "olympus-om-4",
    dataSource: "system",
    make: "Olympus",
    model: "OM-4",
    type: "SLR",
    filmFormat: "35mm",
    mount: "OM",
    disposable: false,
    halfFrame: false,
    releaseDate: "1983",
    minShutterSpeed: 1 / 2000,
    maxShutterSpeed: 1,
  },
  {
    id: "nikon-fa",
    dataSource: "system",
    make: "Nikon",
    model: "FA",
    type: "SLR",
    filmFormat: "35mm",
    mount: "F",
    disposable: false,
    halfFrame: false,
    releaseDate: "1983",
    minShutterSpeed: 1 / 4000,
    maxShutterSpeed: 1,
  },
  {
    id: "canon-a1",
    dataSource: "system",
    make: "Canon",
    model: "A-1",
    type: "SLR",
    filmFormat: "35mm",
    mount: "FD",
    disposable: false,
    halfFrame: false,
    releaseDate: "1978",
    minShutterSpeed: 1 / 1000,
    maxShutterSpeed: 1,
  },
  {
    id: "pentax-lx",
    dataSource: "system",
    make: "Pentax",
    model: "LX",
    type: "SLR",
    filmFormat: "35mm",
    mount: "K",
    disposable: false,
    halfFrame: false,
    releaseDate: "1980",
    minShutterSpeed: 1 / 2000,
    maxShutterSpeed: 1,
  },
  {
    id: "minolta-xd-11",
    dataSource: "system",
    make: "Minolta",
    model: "XD-11",
    type: "SLR",
    filmFormat: "35mm",
    mount: "SR",
    disposable: false,
    halfFrame: false,
    releaseDate: "1977",
    minShutterSpeed: 1 / 1000,
    maxShutterSpeed: 1,
  },
  {
    id: "nikon-fm10",
    dataSource: "system",
    make: "Nikon",
    model: "FM10",
    type: "SLR",
    filmFormat: "35mm",
    mount: "F",
    disposable: false,
    halfFrame: false,
    releaseDate: "1995",
    minShutterSpeed: 1 / 2000,
    maxShutterSpeed: 1,
  },
  {
    id: "canon-t90",
    dataSource: "system",
    make: "Canon",
    model: "T90",
    type: "SLR",
    filmFormat: "35mm",
    mount: "FD",
    disposable: false,
    halfFrame: false,
    releaseDate: "1986",
    minShutterSpeed: 1 / 4000,
    maxShutterSpeed: 1,
  },
  {
    id: "leica-r8",
    dataSource: "system",
    make: "Leica",
    model: "R8",
    type: "SLR",
    filmFormat: "35mm",
    mount: "R",
    disposable: false,
    halfFrame: false,
    releaseDate: "1996",
    minShutterSpeed: 1 / 8000,
    maxShutterSpeed: 1,
  },
  {
    id: "pentax-spotmatic",
    dataSource: "system",
    make: "Pentax",
    model: "Spotmatic",
    type: "SLR",
    filmFormat: "35mm",
    mount: "M42",
    disposable: false,
    halfFrame: false,
    releaseDate: "1964",
    minShutterSpeed: 1 / 1000,
    maxShutterSpeed: 1,
  },
  {
    id: "minolta-srt-101",
    dataSource: "system",
    make: "Minolta",
    model: "SRT-101",
    type: "SLR",
    filmFormat: "35mm",
    mount: "SR",
    disposable: false,
    halfFrame: false,
    releaseDate: "1966",
    minShutterSpeed: 1 / 1000,
    maxShutterSpeed: 1,
  },
];

export const lensTypes: LensType[] = [
  {
    id: "olympus-om-50mm-f1.8",
    dataSource: "system",
    make: "Olympus",
    model: "OM 50mm f/1.8",
    type: "prime",
    releaseDate: "1978",
    minFocalLength: 50,
    maxFocalLength: 50,
    maxAperture: 1.8,
    minAperture: 16,
    mount: "OM",
  },
  {
    id: "canon-ef-85mm-f1.8",
    dataSource: "user",
    make: "Canon",
    model: "EF 85mm f/1.8",
    type: "prime",
    releaseDate: "1992",
    minFocalLength: 85,
    maxFocalLength: 85,
    maxAperture: 1.8,
    minAperture: 22,
    mount: "EF",
  },
  {
    id: "nikon-24-70mm-f2.8",
    dataSource: "system",
    make: "Nikon",
    model: "24-70mm f/2.8",
    type: "zoom",
    releaseDate: "2007",
    minFocalLength: 24,
    maxFocalLength: 70,
    maxAperture: 2.8,
    minAperture: 22,
    mount: "F",
  },
  {
    id: "sony-16-35mm-f4",
    dataSource: "user",
    make: "Sony",
    model: "16-35mm f/4",
    type: "zoom",
    releaseDate: "2014",
    minFocalLength: 16,
    maxFocalLength: 35,
    maxAperture: 4,
    minAperture: 22,
    mount: "E",
  },
  {
    id: "pentax-50mm-f1.4",
    dataSource: "system",
    make: "Pentax",
    model: "50mm f/1.4",
    type: "prime",
    releaseDate: "1971",
    minFocalLength: 50,
    maxFocalLength: 50,
    maxAperture: 1.4,
    minAperture: 22,
    mount: "K",
  },
  {
    id: "fuji-x-35mm-f2",
    dataSource: "user",
    make: "Fujifilm",
    model: "X 35mm f/2",
    type: "prime",
    releaseDate: "2015",
    minFocalLength: 35,
    maxFocalLength: 35,
    maxAperture: 2,
    minAperture: 16,
    mount: "X",
  },
  {
    id: "leica-m-90mm-f2.5",
    dataSource: "system",
    make: "Leica",
    model: "M 90mm f/2.5",
    type: "prime",
    releaseDate: "2008",
    minFocalLength: 90,
    maxFocalLength: 90,
    maxAperture: 2.5,
    minAperture: 16,
    mount: "M",
  },
  {
    id: "sigma-35mm-f1.4",
    dataSource: "user",
    make: "Sigma",
    model: "35mm f/1.4",
    type: "prime",
    releaseDate: "2012",
    minFocalLength: 35,
    maxFocalLength: 35,
    maxAperture: 1.4,
    minAperture: 16,
    mount: "EF",
  },
  {
    id: "tamron-70-200mm-f2.8",
    dataSource: "system",
    make: "Tamron",
    model: "70-200mm f/2.8",
    type: "zoom",
    releaseDate: "2013",
    minFocalLength: 70,
    maxFocalLength: 200,
    maxAperture: 2.8,
    minAperture: 22,
    mount: "F",
  },
  {
    id: "zeiss-otus-85mm-f1.4",
    dataSource: "user",
    make: "Zeiss",
    model: "Otus 85mm f/1.4",
    type: "prime",
    releaseDate: "2014",
    minFocalLength: 85,
    maxFocalLength: 85,
    maxAperture: 1.4,
    minAperture: 16,
    mount: "EF",
  },
  {
    id: "panasonic-25mm-f1.7",
    dataSource: "user",
    make: "Panasonic",
    model: "25mm f/1.7",
    type: "prime",
    releaseDate: "2015",
    minFocalLength: 25,
    maxFocalLength: 25,
    maxAperture: 1.7,
    minAperture: 22,
    mount: "Micro Four Thirds",
  },
  {
    id: "olympus-12-40mm-f2.8",
    dataSource: "system",
    make: "Olympus",
    model: "12-40mm f/2.8",
    type: "zoom",
    releaseDate: "2013",
    minFocalLength: 12,
    maxFocalLength: 40,
    maxAperture: 2.8,
    minAperture: 22,
    mount: "Micro Four Thirds",
  },
  {
    id: "samyang-14mm-f2.8",
    dataSource: "user",
    make: "Samyang",
    model: "14mm f/2.8",
    type: "prime",
    releaseDate: "2009",
    minFocalLength: 14,
    maxFocalLength: 14,
    maxAperture: 2.8,
    minAperture: 22,
    mount: "EF",
  },
  {
    id: "tokina-11-16mm-f2.8",
    dataSource: "system",
    make: "Tokina",
    model: "11-16mm f/2.8",
    type: "zoom",
    releaseDate: "2008",
    minFocalLength: 11,
    maxFocalLength: 16,
    maxAperture: 2.8,
    minAperture: 22,
    mount: "DX",
  },
  {
    id: "sigma-24-105mm-f4",
    dataSource: "user",
    make: "Sigma",
    model: "24-105mm f/4",
    type: "zoom",
    releaseDate: "2013",
    minFocalLength: 24,
    maxFocalLength: 105,
    maxAperture: 4,
    minAperture: 22,
    mount: "EF",
  },
  {
    id: "tamron-28-75mm-f2.8",
    dataSource: "system",
    make: "Tamron",
    model: "28-75mm f/2.8",
    type: "zoom",
    releaseDate: "2018",
    minFocalLength: 28,
    maxFocalLength: 75,
    maxAperture: 2.8,
    minAperture: 22,
    mount: "E",
  },
  {
    id: "nikon-50mm-f1.4",
    dataSource: "user",
    make: "Nikon",
    model: "50mm f/1.4",
    type: "prime",
    releaseDate: "1977",
    minFocalLength: 50,
    maxFocalLength: 50,
    maxAperture: 1.4,
    minAperture: 16,
    mount: "F",
  },
];

export const filmStocks: FilmStock[] = [
  {
    id: "kodak-portra-400",
    dataSource: "system",
    name: "Kodak Portra 400",
    type: "color",
    iso: 400,
  },
  {
    id: "kodak-tri-x-400",
    dataSource: "system",
    name: "Kodak Tri-X 400",
    type: "bw",
    iso: 400,
  },
  {
    id: "ilford-hp5-plus",
    dataSource: "system",
    name: "Ilford HP5 Plus",
    type: "bw",
    iso: 400,
  },
  {
    id: "fuji-pro-400h",
    dataSource: "system",
    name: "Fuji Pro 400H",
    type: "color",
    iso: 400,
  },
  {
    id: "kodak-ektar-100",
    dataSource: "system",
    name: "Kodak Ektar 100",
    type: "color",
    iso: 100,
  },
  {
    id: "ilford-delta-3200",
    dataSource: "system",
    name: "Ilford Delta 3200",
    type: "bw",
    iso: 3200,
  },
  {
    id: "kodak-tmax-100",
    dataSource: "system",
    name: "Kodak T-MAX 100",
    type: "bw",
    iso: 100,
  },
  {
    id: "kodak-tmax-400",
    dataSource: "system",
    name: "Kodak T-MAX 400",
    type: "bw",
    iso: 400,
  },
  {
    id: "fuji-velvia-50",
    dataSource: "system",
    name: "Fuji Velvia 50",
    type: "color",
    iso: 50,
  },
  {
    id: "fuji-velvia-100",
    dataSource: "system",
    name: "Fuji Velvia 100",
    type: "color",
    iso: 100,
  },
  {
    id: "fuji-neopan-acros-100",
    dataSource: "system",
    name: "Fuji Neopan Acros 100",
    type: "bw",
    iso: 100,
  },
  {
    id: "ilford-pan-f-plus-50",
    dataSource: "system",
    name: "Ilford Pan F Plus 50",
    type: "bw",
    iso: 50,
  },
  {
    id: "ilford-fp4-plus-125",
    dataSource: "system",
    name: "Ilford FP4 Plus 125",
    type: "bw",
    iso: 125,
  },
  {
    id: "ilford-sfx-200",
    dataSource: "system",
    name: "Ilford SFX 200",
    type: "bw",
    iso: 200,
  },
  {
    id: "kodak-gold-200",
    dataSource: "system",
    name: "Kodak Gold 200",
    type: "color",
    iso: 200,
  },
  {
    id: "kodak-ultramax-400",
    dataSource: "system",
    name: "Kodak Ultramax 400",
    type: "color",
    iso: 400,
  },
  {
    id: "fuji-superia-200",
    dataSource: "system",
    name: "Fuji Superia 200",
    type: "color",
    iso: 200,
  },
  {
    id: "fuji-superia-400",
    dataSource: "system",
    name: "Fuji Superia 400",
    type: "color",
    iso: 400,
  },
  {
    id: "fuji-superia-800",
    dataSource: "system",
    name: "Fuji Superia 800",
    type: "color",
    iso: 800,
  },
  {
    id: "kodak-portra-160",
    dataSource: "system",
    name: "Kodak Portra 160",
    type: "color",
    iso: 160,
  },
  {
    id: "kodak-portra-800",
    dataSource: "system",
    name: "Kodak Portra 800",
    type: "color",
    iso: 800,
  },
  {
    id: "agfa-vista-200",
    dataSource: "system",
    name: "Agfa Vista 200",
    type: "color",
    iso: 200,
  },
  {
    id: "agfa-vista-400",
    dataSource: "system",
    name: "Agfa Vista 400",
    type: "color",
    iso: 400,
  },
  {
    id: "cinestill-50d",
    dataSource: "system",
    name: "CineStill 50D",
    type: "color",
    iso: 50,
  },
  {
    id: "cinestill-800t",
    dataSource: "system",
    name: "CineStill 800T",
    type: "color",
    iso: 800,
  },
  {
    id: "lomography-100",
    dataSource: "system",
    name: "Lomography 100",
    type: "color",
    iso: 100,
  },
  {
    id: "lomography-400",
    dataSource: "system",
    name: "Lomography 400",
    type: "color",
    iso: 400,
  },
  {
    id: "lomography-800",
    dataSource: "system",
    name: "Lomography 800",
    type: "color",
    iso: 800,
  },
  {
    id: "rollei-rpx-25",
    dataSource: "system",
    name: "Rollei RPX 25",
    type: "bw",
    iso: 25,
  },
  {
    id: "rollei-rpx-100",
    dataSource: "system",
    name: "Rollei RPX 100",
    type: "bw",
    iso: 100,
  },
  {
    id: "rollei-rpx-400",
    dataSource: "system",
    name: "Rollei RPX 400",
    type: "bw",
    iso: 400,
  },
  {
    id: "bergger-pancro-400",
    dataSource: "system",
    name: "Bergger Pancro 400",
    type: "bw",
    iso: 400,
  },
  {
    id: "foma-fomapan-100",
    dataSource: "system",
    name: "Foma Fomapan 100",
    type: "bw",
    iso: 100,
  },
  {
    id: "foma-fomapan-200",
    dataSource: "system",
    name: "Foma Fomapan 200",
    type: "bw",
    iso: 200,
  },
  {
    id: "foma-fomapan-400",
    dataSource: "system",
    name: "Foma Fomapan 400",
    type: "bw",
    iso: 400,
  },
];
